### ISSUE TITLE
Lỗi start.py

### ISSUE THREAD

**Issue by quangvinh9x** [phanmemkhoinghiep/vietbot_online#1]
![image](https://user-images.githubusercontent.com/71742958/154079611-70e73c36-0b51-4e71-a1cc-9417269b1b5e.png)

Em chạy các bước, test thử loa mic ok rồi, config lấy accesskey của picovoice rồi. Sau create start.py, chạy file báo lỗi như hình

**Comment by phanmemkhoinghiep** [comment]
Do Pi zero w 1 và các phần cứng dùng CPU Armv6 đó, chuyển sang Armv7 là OK

**Comment by fdkgenie** [comment]
Mình cài trên Pi Zero 2 W (armv7) cũng bị lỗi khi chạy start.py như vậy. Nhờ tác giả trợ giúp. Rất cám ơn đóng góp của tác giả

**Comment by phanmemkhoinghiep** [comment]
> Mình cài trên Pi Zero 2 W (armv7) cũng bị lỗi khi chạy start.py như vậy. Nhờ tác giả trợ giúp. Rất cám ơn đóng góp của tác giả

Bạn đã xử lý được chưa?

**Comment by fdkgenie** [comment]
> > Mình cài trên Pi Zero 2 W (armv7) cũng bị lỗi khi chạy start.py như vậy. Nhờ tác giả trợ giúp. Rất cám ơn đóng góp của tác giả
> 
> Đã có nhiều phiên bản fixed lỗi từ thời điểm báo. Ko biết bạn đã xử lý được chưa?

Mình vừa thử lại thấy vẫn bị lỗi trên (thử cả 2 file main.so dung lượng 749KB và 424KB), nhờ bạn kiểm tra lại giúp. Tks bạn!

**Comment by phanmemkhoinghiep** [comment]
> Mình vừa thử lại thấy vẫn bị lỗi trên (thử cả 2 file main.so dung lượng 749KB và 424KB), nhờ bạn kiểm tra lại giúp. Tks bạn!

Bạn cần flash phiên bản raspbian OS Lite 32 bit, sau đó tiến hành cài đặt theo guide 022_software_enviroment_installation_guide.md và tối ưu theo 023_software_enviroment_installation_optimize.md. Nếu flash từ imge trong link 021_software_enviroment_installation_guide.md rồi gitcode sẽ bị lỗi

**Comment by fdkgenie** [comment]
Mình cài từ đầu chứ ko flash file img làm sẵn (ko hiểu sao flash img sẵn ko vào đc wifi dù đã tạo file wpa_supplicant như hướng dẫn)

**Comment by phanmemkhoinghiep** [comment]
> Mình cài từ đầu chứ ko flash file img làm sẵn (ko hiểu sao flash img sẵn ko vào đc wifi dù đã tạo file wpa_supplicant như hướng dẫn)

Trong nhánh Beta đã cập nhật lại cả file img, cả hướng dẫn cài mới chi tiết nhé

**Comment by fdkgenie** [comment]
> 

Mình remove folder vietbot_online và cài lại từ đầu nhánh beta rồi, đến bước chạy start.py vẫn bị lỗi như trên :(

**Comment by fdkgenie** [comment]
Hôm nay mình cài trên Pi3B+ với Mics-2 HAT thì chạy start.py không báo lỗi trên mà báo lỗi khác:
`pi@raspberrypi:~/vietbot_online/src $ python3 start.py
pygame 2.1.0 (SDL 2.0.14, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/pi/vietbot_online/src/start.py", line 6, in <module>
    import main
  File "main.py", line 44, in init main
  File "led_controll.py", line 269, in init led_controll
  File "led_controll.py", line 166, in led_controll.Pixels.__init__
TypeError: 'APA102' object is not callable`
Nhờ bạn chỉ giúp cách fix

**Comment by phanmemkhoinghiep** [comment]
> Hôm nay mình cài trên Pi3B+ với Mics-2 HAT thì chạy start.py không báo lỗi trên mà báo lỗi khác: `pi@raspberrypi:~/vietbot_online/src $ python3 start.py pygame 2.1.0 (SDL 2.0.14, Python 3.9.2) Hello from the pygame community. https://www.pygame.org/contribute.html Traceback (most recent call last): File "/home/pi/vietbot_online/src/start.py", line 6, in <module> import main File "main.py", line 44, in init main File "led_controll.py", line 269, in init led_controll File "led_controll.py", line 166, in led_controll.Pixels.__init__ TypeError: 'APA102' object is not callable` Nhờ bạn chỉ giúp cách fix

Bạn phải chọn đúng loại Mic trong create_config nhé, loại nào dùng thì enbale lên
